# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "10Diego10") %>

development:
  primary:
    <<: *default
    database: menu_express_development
  cable:
    <<: *default
    database: menu_express_development
  queue:
    <<: *default
    database: menu_express_development

test:
  primary:
    <<: *default
    database: menu_express_test
  cable:
    <<: *default
    database: menu_express_test
  queue:
    <<: *default
    database: menu_express_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
